### PR TITLE
Possible NPE when servers is null.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
🐝 . Seems no other usages in the class.
BTW, I would prefer to see proper annotations, etc. NIT

**Comment by christ66** [comment]
CI job failed because it's using JDK 7. The binaries are JDK 8.

**Comment by casz** [comment]
Thanks for the PR, good catch 👍 Yes annotations would also prefer annotations.

**Comment by christ66** [comment]
I'll add an `@CheckForNull` annotation.

**Comment by christ66** [comment]
@casz Added.

**Comment by casz** [comment]
Added a check for known null at newInstance 👍

**Pull request merged**
