### PR TITLE
MicroFocus contributed -Method Parameter interchanged in Hist command

### PR DESCRIPTION
**Pull request by PoojaVishal**
hist command failed as parameters passed to hist command swapped between dateRange and transactionTypes which led mal formation of hist command.

### CODE REVIEW

**Comment by PoojaVishal** [comment]
@casz now?

**Comment by PoojaVishal** [comment]
@casz Is this PR ok?

**Comment by casz** [comment]
no your starting the PR from your master branch and it didn't fix the master branch :)

When you open a new pull request you have to choose the branch on the right side

image

**Comment by PoojaVishal** [comment]
@casz 
image

**Comment by PoojaVishal** [comment]
This way? 
Shall i create this way?

**Comment by casz** [comment]
You need to change the branch, marked in green
image

**Comment by PoojaVishal** [comment]
image

@casz this is good?

**Comment by PoojaVishal** [comment]
image
@casz  this where i create PR

**Comment by casz** [comment]
no.

You need to push your local branch with your changes that is not behind jenkinsci:master

image

**Comment by PoojaVishal** [comment]
image

**Comment by PoojaVishal** [comment]
now shall i create PR from where i have highlighted?
@casz

**Pull request closed without merging**
