### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by casz**
- [x] Extension point for different checkout strategy such as workspace, and reference tree.
- [ ] Extension point for exclusion of changes (include/exclude path, exclude user, etc)
- [ ] Ensure Jenkins can both make workspace and change workspace. Also move it out of the way if blocking checkout.
- [x] Reduce checkboxes, provide extensions if needed
- [x] Deprecate AccurevServer, use url and credentials on job
- [ ] Complete all extension points implementations
- [ ] Complete Accurev CLI Interface implementation
- [ ] Use accurev update to check if polling has changes, if so dive deeper with hist and check on our end if revision is excluded (drop the -k nightmare for accurev)
- [x] Migration with Unit Test
- [x] Consider if all checkboxes on global config are needed. Resolution: Extension on job!
- [ ] AdministrativeMonitor flag failed migration for Job.
- [ ] Find solution to Unit Test Accurev (Docker Image of Accurev Server and Client? Need to clear it with MicroFocus)

Reason for this is current abstract implementation is complex, providing extension points makes it easy to introduce new behaviour!
Relying too much on user input from job configuration and current server configuration, we should rely more on accurev's information about streams/workspace and rely more on plugin specific behaviour to reduce complexity.

If possible once this work is done, I would like to move focus towards SCM API and Branch API to support multibranch pipeline 👍 
SCM API provides events and I believe that is achieved through webhooks, I could be wrong, we would implement the same behaviour as other branch source plugins, scan repo (depot) for changes on set interval usually but otherwise rely on SCM events. I would like to create a repo for the perl script that implements the webhook for on the accurev side, server-wide (repo).

### CODE REVIEW

**Comment by rym002** [comment]
I use reference trees extensively. Please do not remove this

**Comment by casz** [comment]
Good enough for me, one more extension to the list 👍

**Comment by itavero** [comment]
@rym002 @casz I've never used reference trees, but from my experience with the AccuRev CLI commands, I would not expect most of the commands to be any different for a workspace than for a reference tree.
Only the mk/ch commands seem different to me.

**Comment by casz** [comment]
Checkout strategy for each implementation

Reference tree: "Requires Jenkins workspace"
  Relocate to correct node
  Perform update, to populate changed files

Snapshot checkout:
  Create snapshot from stream
  Populate snapshot

Use "Accurev Workspace": "Requires Jenkins workspace"
  Create workspace if missing.
  Check reparent need.
  Relocate to correct node
  Populate workspace

Stream/Workspace (Default implementation):
  Populate

General checkout:
  Check for missing files, if so populate

**Comment by casz** [comment]
Current UI implementation, removed the need for advanced option in regards to the additonal behaviours :+1:
image

**Comment by casz** [comment]
I will try and provide migration for any breaking changes :+1: when feasible. Most if not all should be feasible!

**Comment by casz** [comment]
This is how the new UI will look:
image
Moved server URL to job config, and moved advanced server options into global.
image

**Comment by casz** [comment]
Closing in favor for a branch on jenkinsci/accurev-plugin

**Pull request closed without merging**
