### PR TITLE
[JENKINS-44748] Ensure defunct files are removed from populating files

### PR DESCRIPTION
**Pull request by casz**
[JENKINS-44748](https://issues.jenkins-ci.org/browse/JENKINS-44748)

### CODE REVIEW

**Comment by hadwen** [comment]
build the above fixed locally and installed it on the system showing the problem, it did not resolve the issue.

**Comment by casz** [comment]
@hadwen you don't have to build it locally nextime :)
You can grab the artifacts from the https://ci.jenkins.io
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Faccurev-plugin/detail/PR-56/1/artifacts

Will have to figure out a command that can give me a list of new files while excluding defunct files.
History command does not suffice.

**Comment by casz** [comment]
Should be able use accurev files to check if files are defunct-ed and remove them from the list.

Problem is accurev treats a defunct as a promote on stream when promoted from workspace and IMHO this is just bad design. So you can't really rely on history, you have to use secondary commands to figure out if files are defuncted

I just defunct-ed and promoted this file.
```
$ accurev hist -s workspace -t now
transaction 20190; defunct; 2017/06/08 17:11:45 ; user: josp
  # a
  \.\readme.txt 99/1 (99/1)
  ancestor: (21/1)

$ accurev hist -s exp_app_falcon_dev -t now
transaction 20191; promote; 2017/06/08 17:12:11 ; user: casz
  # defunct-ed
  \.\readme.txt 18/2 (99/1)
```

**Comment by casz** [comment]
@hadwen I tested it locally and was able to get it working.

**Comment by hadwen** [comment]
agreed, downloaded and tested with artifact associated with the PR and it resolves the issue.

**Comment by casz** [comment]
Cheers

**Comment by casz** [comment]
Released as 0.7.14

**Pull request merged**
