### PR TITLE
Code cleanup, Jenkins-4369 FIX, Log spamming, Javadoc

### PR DESCRIPTION
**Pull request by casz**
Code cleanup and updated to Jenkins plugin 2.13

Fixed failing injected tests due to missing escape by default parameter in jelly files. [Fixed failing test](https://github.com/jenkinsci/accurev-plugin/commit/39f5f1d358fd5bc6a92585dec10893049e992e59)

Transaction Size was spamming the log a bit too much. [Spamming log](https://github.com/jenkinsci/accurev-plugin/commit/a888905f0f2a96dcf09d4211a447463ce87085e6)

Noticed the pull request for: 	[JENKINS-4369 Fix - Workspace relocation check false positivities](https://github.com/jenkinsci/accurev-plugin/pull/11)
Though the codebase has changed it was easy too see where it was needed. [4369 Fix](https://github.com/jenkinsci/accurev-plugin/commit/c825f7c2d4ca68630ae9e6e6517f080e7729031d)
Does indeed fix the issue. We had run into this issue in the past.

Did the necessary javadoc updating for Doc linting in Java 8

### CODE REVIEW

**Comment by casz** [comment]
Attempting to update to Jenkins 2.7 stay tuned.

**Comment by casz** [comment]
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:check (findbugs) on project accurev: failed with 43 bugs and 0 errors -> [Help 1]

Going to try and resolve the 43 bugs.

**Comment by casz** [comment]
Now that it is working. All that is left so far is Deprecation warnings.

**Comment by daniel-beck** [comment]
@rym002 The author of this PR asked to be made maintainer of this plugin. Any objections, as the user creating the last few releases?

Reference: https://groups.google.com/d/msg/jenkinsci-dev/SdNcPm5q_vY/wQ0rYg8uCQAJ

**Comment by casz** [comment]
Like to mention that I am working for a company, who actively use accurev. We are invested in maintaining this plugin.

**Comment by casz** [comment]
@rym002 do you have any objections to the changes?

**Pull request merged**
