### PR TITLE
MicroFocus contributed -Method Parameter interchanged in Hist command

### PR DESCRIPTION
**Pull request by PoojaVishal**
hist command failed as parameters passed to hist command swapped between dateRange and transactionTypes which led mal formation of hist command.

### CODE REVIEW

**Comment by PoojaVishal** [comment]
@casz  please accept the PR. and merge the changes.
Its very small bug.

**Comment by PoojaVishal** [comment]
@casz please tell me if did something wrong.

**Comment by PoojaVishal** [comment]
@casz please tell me if I did something incorrect again.

**Comment by casz** [comment]
You did it correctly :sweat:

Could be better if you remembered to start new work on a new branch start that starts from jenkinsci/accurev-plugin to avoid this mess :)

```
git fetch jenkinsci
git checkout -b my_new_branch jenkinsci/master
git add .
git commit -m "my new changes"
git push -u
```

Now you should be able to create a pull request from `my_new_branch`

**Comment by PoojaVishal** [comment]
@casz I had directly made changes in master rather then creating a branch.. may b that's wrong way of doing it..

But what git push -u? -u stand for?

**Comment by PoojaVishal** [comment]
@ casz can we publish this change in same  21 release? So that we can notify our customer..

**Comment by casz** [comment]
[`git push -u` explained](https://explainshell.com/explain?cmd=git+push+-u)

No funky re-release of packages. We have to bump the version. I wonder why you even ask that. 🤔

**Comment by NilkamalDey** [comment]
@casz please release this build. Tested build #83  & this look good.

**Comment by PoojaVishal** [comment]
7.22 release is out.

Regards,
Pooja

**Comment by casz** [comment]
@NilkamalDey I suggest you [watch the releases](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository) or [watch the repo](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-repositories) to get notifications.

image

**Comment by PoojaVishal** [comment]
@casz , Thank you so much. You saved the Day!

**Comment by PoojaVishal** [comment]
@casz I see Synctime parameter in AccurevSCM.java class but i dont find its reference in config.jelly or any UI code.
Where and how to use this?
I facing this issue while polling.
image

**Comment by casz** [comment]
Should not be accurev that attempts to fix the clock as they may not have admin permission to do so

**Comment by PoojaVishal** [comment]
In Command promt i ran "accurev synctime -H host:port" to fix this exception. 
Is there any other way we solve this sync time issue?

**Comment by casz** [comment]
it's in the UI under advanced tab: https://github.com/jenkinsci/accurev-plugin/blob/e01b1affe0b3fb648a53b4928907e366306cd025/src/main/resources/hudson/plugins/accurev/AccurevSCM/AccurevServer/config.groovy#L25

**Comment by PoojaVishal** [comment]
ok. Got it.. May be we should name it Synchronize Time for AccuRev CLI operations rather then Synchronize AccuRev CLI Operations. :)

**Pull request merged**
