### PR TITLE
Update help message for sub path

### PR DESCRIPTION
**Pull request by PoojaVishal**
I have just updated a help document for SubPath.html in this PR.
Added example with "*" to pick changes in sub-directories while polling.
please review and merge.

### CODE REVIEW

**Comment by casz** [comment]
Please rebase your pull request with master

**Comment by casz** [comment]
Also don't create PRs from master branch

**Comment by PoojaVishal** [comment]
shall i delete this pull request and create new?
i dono how to rebase a PR

**Comment by casz** [comment]
we been over this before: https://github.com/jenkinsci/accurev-plugin/pull/61#issuecomment-385343623

**Comment by PoojaVishal** [comment]
Rebasing is nightmare..
please see now. i squashed my commits

**Comment by casz** [comment]
@PoojaVishal No luck on the rebase or at least you did not manage to `git push --force`


if you prefer you can create a branch from `upstream/master` and `cherry-pick` or simply recommit your changes.

and then open a new PR.

as I wrote in the other PR, please remember to reset or sync up with upstream 😄

If you do not have upstream setup:
```
git remote add upstream https://github.com/jenkinsci/accurev-plugin.git
git fetch upstream
```

```
git checkout -b mybranch upstream/master
``

then either cherry-pick or just carry over your changes.

```
git cherry-pick b6927a3d972558ef092f77d9686cba96517ddca5
```

**Comment by PoojaVishal** [comment]
i had done hard reset before i commit my changes. Dont know when this new change was pushed.
my branch is also upto date it said when i did git status before committing my changes.

Only AccurevSCM has conflict in merging.

Is there any way i can hard reset only conflict file?

**Comment by casz** [comment]
if you have added `upstream` remote like shown above you can something like this:
```
git reset --hard upstream/master
git git cherry-pick b6927a3d972558ef092f77d9686cba96517ddca5
git push --force
```

**Comment by PoojaVishal** [comment]
git cherry pick didn't work.
image

i committed that subpath change and force pushed.

**Comment by PoojaVishal** [comment]
Is it alright now?

**Comment by casz** [comment]
Yup looks better :)

**Comment by PoojaVishal** [comment]
i have some doubts.
My branch is origin/master?
and master branch is jenkinsci/master?

**Comment by PoojaVishal** [comment]
And y was there conflict in AccurevSCM while rebasing? 
As i didnt make any changes in that file at all.

**Comment by casz** [comment]
git is a distributed VCS and that's why you been running into issues because you forget to pull your recently merged changes on `jenkinsci` into your `origin` :)

You should be able to verify with
```
git remote -v
```
Your `origin` points to `github.com/PoojaVishal/accurev-plugin`
Your `jenkinsci` points to `github.com/PoojaVishal/accurev-plugin`


This is the output from my `accurev-plugin` repo
```
$ git remote -v
jenkinsci       git@github.com:jenkinsci/accurev-plugin.git (fetch)
jenkinsci       git@github.com:jenkinsci/accurev-plugin.git (push)
origin  https://github.com/casz/accurev-plugin.git (fetch)
origin  https://github.com/casz/accurev-plugin.git (push)
```

**Comment by PoojaVishal** [comment]
thank you @casz .
Everytime i feel that i understand git  , i stumble upon rebase/squash/comits/remote/master/ etc etc and end up confused.
Please bare with me.

**Comment by PoojaVishal** [comment]
Will you merge my changes now or should is there something from my side?

**Comment by PoojaVishal** [comment]
Will you Please merge my changes ?
Squash and Merge button is disabled to me.
Any idea y?

**Comment by PoojaVishal** [comment]
@casz Kindly merge the changes to master.

**Comment by PoojaVishal** [comment]
It merges automatically on closing the PR?

**Comment by casz** [comment]
No, it sends a webhook to https://ci.jenkins.io so that the CI can be run

**Comment by PoojaVishal** [comment]
@casz  After build successful , subpath.html changes will be included?
or after merge and PR is closed?

**Comment by PoojaVishal** [comment]
@casz Its still building.. been 6 n half hours already.
Does it takes this long?

**Comment by PoojaVishal** [comment]
@casz Build failed..
Please see what we can do..

**Comment by PoojaVishal** [comment]
@casz  shall i close this PR and open new PR from my branch.?
Please suggest.

**Comment by casz** [comment]
Not sure why we have to wait 😆

**Comment by casz** [comment]
While your at it, feel free to test https://github.com/casz/docker-accurev 😆

**Comment by PoojaVishal** [comment]
:+1:

**Pull request merged**
