### PR TITLE
Request for Jenkins plug-in to have "Validate" button to test connection/login

### PR DESCRIPTION
**Pull request by PoojaVishal**
This is the COULD-HAVE  requested by customer.

### CODE REVIEW

**Comment by casz** [comment]
Please rebase on to Jenkinsci/master

**Comment by casz** [comment]
If you had rebased successfully this would be the only commit: 
image

This should do it 👍 
```
git remote add jenkinsci https://github.com/jenkinsci/accurev-plugin.git
git fetch jenkinsci
git rebase jenkinsci/master
git push -f
```

**Comment by PoojaVishal** [comment]
Now?
there were commits with conflicts.. i did git rebase --skip for them. as it was not letting me do git push -f.
image

**Comment by casz** [comment]
Almost 👍 could you try again you messed up one of the commits by not resolving a conflict:
https://github.com/jenkinsci/accurev-plugin/pull/61/commits/05d71cbc3da9082c7a91d2626aeb9c6d0d8eaf97

**Comment by PoojaVishal** [comment]
resolved and pushed..
Fine now?

**Comment by casz** [comment]
Now just to get the full workflow of git, would you mind squashing into one commit? 😁 
Here you can use rebase interactively here.

`git rebase -i HEAD~3`

**Comment by PoojaVishal** [comment]
I did rebase  -i HEAD~3, got below window where i replaced pick with squash.
image

next what should i do? Just close the cmd promt?

**Comment by PoojaVishal** [comment]
please see now.

**Comment by casz** [comment]
Do you have visual code installed or another editor? So you don't have to deal with VIM 😅 

If you have visual code installed, I suggest you change your editor for git.

`git config --global core.editor "code --wait"` or change it to whatever editor you have (google should help you)

When you run rebase interactively you want to save and exit the editor which will actually do the steps.

**Comment by PoojaVishal** [comment]
I have squashed it.
image
 
Thank you for your suggestion on editor.

**Comment by PoojaVishal** [comment]
so is this change pushed to master?

**Comment by casz** [comment]
@PoojaVishal now it is :)

**Comment by PoojaVishal** [comment]
thank you so much.

**Comment by casz** [comment]
@PoojaVishal before starting new work I suggest you reset your master branch to jenkinsci/master

```
git fetch jenkinsci
git reset --hard jenkinsci/master
```

this will ensure you don't have to rebase. If you have already have some work you have not yet committed you want to commit and rebase 👍 or you can also stash your work with `git stash`, then reset to jenkinsci/master, and then `git stash pop`

**Comment by PoojaVishal** [comment]
Will keep this in mind.

**Pull request merged**
